spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root123}
  zipkin:
    sender:
      type: rabbit
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    loadbalancer:
      retry:
        enabled: true
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.l.library
  local:
    # 短時本地緩存，主要用于要求时效较高的配置
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000
logging:
  level:
    com.l.library: DEBUG
    org.springframework.web: debug
    org.springframework.security: debug
  path: logs/
  file:
    max-size: 1GB
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  configuration:
    # 开启驼峰功能。
    map-underscore-to-camel-case: true
