spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  # 链路追踪
  zipkin:
    enabled: true
    sender:
      type: rabbit

  sleuth:
    sampler:
      probability: 1.0

  mvc:
    throw-exception-if-no-handler-found: true

  # JWT的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456

  cloud:
    loadbalancer:
      retry:
        enabled: true
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: DEBUG
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  configuration:
    # 开启驼峰功能
    map-underscore-to-camel-case: true
