version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: sc-nacos-standalone
    networks:
      - sc-net
    environment:
      - PREFER_HOST_MOOE=hostname
      - MOOE=standalone
    volumes:
      - ../data/nacos-server:/logs/:/home/nacos/logs
    ports:
    - "8848:8848"